### ISSUE TITLE
how to find Firebase_RTDB_Endpoint..?

### ISSUE THREAD

**Issue by SandipVermaDev** [ibtesaamahmed/Ecommerce_Shop_App#1]
how to find Firebase_RTDB_Endpoint?

**Comment by ibtesaamahmed** [comment]
After creating your Firebase Real-time Database, You can find the endpoint at the place marked as green in the following picture.

![img](https://github.com/ibtesaamahmed/Ecommerce_Shop_App/assets/57338601/1ec800c4-a4aa-421d-b8df-5d42d6183ae4)
